package lexing;

/**
 * Exception class for errors generated by parsing bad inputs
 */
public class LexError extends Exception {

    /**
     * Create an Exception of type lexing.LexError
     *
     * @param m Message to be passed up to caller
     */
    LexError(String m) {
        super(m);
    }
}
