package org.zp.parser.lexing;

/**
 * Exception class for errors generated by org.zp.parser.parsing bad inputs
 */
public class LexError extends Exception {

    /**
     * Create an Exception of type org.zp.parser.lexing.LexError
     *
     * @param m Message to be passed up to caller
     */
    LexError(String m) {
        super(m);
    }
}
