/**
 * Exception class for errors generated by parsing bad inputs
 */
public class ParseError extends Exception {

    /**
     * Create an Exception of type ParseError
     * @param m Message to be passed up to caller
     */
    ParseError(String m) {
        super(m);
    }
}
